### ISSUE TITLE
Single Delete button is not functioning properly

### ISSUE THREAD

**Issue by divyanshraj0408** [divyanshraj0408/SaveTabs#10]
## The Problem:
On clicking the delete button of any URL, every other URL expect that URL is getting deleted.
## What was expected to happen:
The respective URL of which the button is pressed is supposed to get deleted.

**Comment by myujjawal** [comment]
Hey! I would love to have a go at it. Can you please assign it to me?

**Comment by divyanshraj0408** [comment]
Sure go ahead and if any problem occurs you can ask here.

**Comment by divyanshraj0408** [comment]
Good day @myujjawal , how is the progress on the issue?

**Comment by Hat52** [comment]
This issue is fixed in the new Pr that I have created, along with this issue  I have added the hover effect.

**Comment by divyanshraj0408** [comment]
Thanks @Hat52 for contributing.
