### ISSUE TITLE
Feat: Make the cursor pointer while using buttons.

### ISSUE THREAD

**Issue by divyanshraj0408** [divyanshraj0408/SaveTabs#2]
## The problem
The cursor remains default when hovering over the buttons or clicking them.
## Things to be done 
By changing the cursor property in `style.css` file, this issue can solve this issue.

**Comment by Hat52** [comment]
I would like to work on this issue.

**Comment by sauradip007** [comment]
I would like to take this issue up

**Comment by divyanshraj0408** [comment]
> I would like to work on this issue.
Sure, go ahead.

**Comment by divyanshraj0408** [comment]
> I would like to work on this issue.

Sure, go ahead @Hat52 .

**Comment by divyanshraj0408** [comment]
> I would like to take this issue up

Thankyou @sauradip007 for helping but it seems the issue is already taken. You can still help by reviewing the PR. 😊

**Comment by sauradip007** [comment]
sure , no problem. 😃 👍

**Comment by sauradip007** [comment]
hey , just checking up. Has the issue been resolved yet? 😃

**Comment by divyanshraj0408** [comment]
> hey , just checking up. Has the issue been resolved yet? 😃

Apparently there is no response from @Hat52, lets wait for tomorrow morning, then we can consider reassigning, thanks for your time🙌😊

**Comment by Hat52** [comment]
Hi, I will start working on it. I thought I should respond once I am done😊

**Comment by divyanshraj0408** [comment]
> Hi, I will start working on it. I thought I should respond once I am done😊

Go for it.

**Comment by sauradip007** [comment]
I would like to take this issue up

**Comment by divyanshraj0408** [comment]
> I would like to take this issue up

You are assigned. Go for it.

**Comment by Hat52** [comment]
I have created a pull request

**Comment by sauradip007** [comment]
done
