### ISSUE TITLE
Change UI of saved tabs

### ISSUE THREAD

**Issue by Hat52** [divyanshraj0408/SaveTabs#5]
I would like to change the UI of the list of saved tabs, the image attached has the changes that I have implemented.
![Screenshot from 2022-01-24 23-56-13](https://user-images.githubusercontent.com/44437268/150847000-7c1f62a5-0900-42c4-8204-3adfae99d281.png)
 
If you have any other changes let me.

**Comment by divyanshraj0408** [comment]
This actually looks great! Do you think we should also change font colors?

**Comment by Hat52** [comment]
Which font do you have in mind?

**Comment by divyanshraj0408** [comment]
I don't have any particular idea, I am not very good at choosing colors. You can make a pr with your idea then we can discuss any changes if needed. 🙌

**Comment by Hat52** [comment]
Okay.
